Update patch set 2
Patch Set 2:

this breaks CrOS builds which uses newer llvm & -Werror -Wswitch

../src/common/dwarf/dwarf2reader.cc:179:11: error: 18 enumeration values not handled in switch: 'DW_FORM_strx', 'DW_FORM_addrx', 'DW_FORM_ref_sup4'... [-Werror,-Wswitch]
  switch (form) {
../src/common/dwarf/dwarf2reader.cc:424:11: error: 18 enumeration values not handled in switch: 'DW_FORM_strx', 'DW_FORM_addrx', 'DW_FORM_ref_sup4'... [-Werror,-Wswitch]
  switch (form) {

Patch-set: 2
CC: Gerrit User 1000768 <1000768@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>