Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> https://crrev.com/c/2153333 some issues, but not all
> 
> src/common/dwarf/dwarf2reader_die_unittest.cc:88:45: error: unknown type name 'int64'
>                                             int64 data));
> 
> standard types are int64_t ...

Oops! I missed some in tests because I forgot that `make check` builds things that `make` doesn't. Fixed over at https://chromium-review.googlesource.com/c/breakpad/breakpad/+/2153567

Patch-set: 1
Reviewer: Gerrit User 1172779 <1172779@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>