Fix broken unittest builds on non-Linux
On non-Linux, ToT currently breaks at:

  Undefined symbols for architecture x86_64:
    "google_breakpad::DisassemblerObjdump::TokenizeInstruction(...)":
    "google_breakpad::DisassemblerObjdump::DisassembleInstruction(...)":
  ld: symbol(s) not found for architecture x86_64

This CL fixes the issue by adding the missing stubs for DisassemblerObjdump.

Change-Id: I3d8933a7b3bac29bfe9c3e327871b9977156f2e8