Update patch set 5
Patch Set 5:

i did:

 $ cd ..
 $ mkdir build
 $ cd build
 $ ../src/configure
 $ make distcheck -j32
...
../../src/testing/googletest/include/gtest/internal/gtest-port.h:282:46: fatal error: gtest/internal/custom/gtest-port.h: No such file or directory

and indeed, when you look at your Makefile.am changes, you don't list all the new files.

if your system is getting in the way, then you can use github.  fork our repo (https://github.com/google/breakpad), then push your changes to your fork, then wait for Travis to finish its testing.

Patch-set: 5