Update patch set 3
Patch Set 3:

(1 comment)

Sorry, clipboard malfunction. Only the relevant bit:

FAILED: obj/third_party/breakpad/breakpad_unittests__exec/exception_handler_unittest.o 
/b/c/goma_client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/breakpad/breakpad_unittests__exec/exception_handler_unittest.o.d -DV8_DEPRECATION_WARNINGS -DDCHECK_ALWAYS_ON=1 -DNO_TCMALLOC -DSAFE_BROWSING_DB_REMOTE -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DANDROID -DHAVE_SYS_UIO_H -DANDROID_NDK_VERSION_ROLL=r16_1 -DCR_CLANG_REVISION=\"321529-2\" -D__GNU_SOURCE=1 -DCHROMIUM_CXX_TWEAK_INLINES -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGTEST_API_= -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=1 -DGTEST_HAS_TR1_TUPLE=1 -DUNIT_TEST -I../../third_party/breakpad/linux -I../../third_party/breakpad -I../.. -Igen -I../../third_party/breakpad/breakpad/src -I../../third_party/breakpad/breakpad/src/common/android/include -I../../third_party/googletest/src/googletest/include -I../../third_party/googletest/custom -I../../third_party/googletest/src/googlemock/include -Wno-unused-value -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -fcolor-diagnostics -no-canonical-prefixes -ffunction-sections -fno-short-enums --target=aarch64-linux-android -isystem../../third_party/android_ndk/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -D__NDK_FPABI__= -Oz -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fdebug-info-for-profiling -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Werror -Wall -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -Wno-enum-compare-switch -Wno-tautological-unsigned-zero-compare -Wno-null-pointer-arithmetic -Wno-tautological-constant-compare -Wtautological-constant-out-of-range-compare -fPIE -std=gnu++14 -fno-exceptions -fno-rtti -isystem../../third_party/android_ndk/sources/cxx-stl/llvm-libc++/include -isystem../../third_party/android_ndk/sources/cxx-stl/llvm-libc++abi/include -isystem../../third_party/android_ndk/sources/android/support/include --sysroot=../../third_party/android_ndk/sysroot -fvisibility-inlines-hidden -c ../../third_party/breakpad/breakpad/src/client/linux/handler/exception_handler_unittest.cc -o obj/third_party/breakpad/breakpad_unittests__exec/exception_handler_unittest.o
../../third_party/breakpad/breakpad/src/client/linux/handler/exception_handler_unittest.cc:267:3: error: unknown type name 'pthread_barrier_t'; did you mean 'pthread_attr_t'?
  pthread_barrier_t* b = reinterpret_cast<pthread_barrier_t*>(b_ptr);
  ^~~~~~~~~~~~~~~~~
  pthread_attr_t
../../third_party/android_ndk/sysroot/usr/include/bits/pthread_types.h:45:3: note: 'pthread_attr_t' declared here
} pthread_attr_t;
  ^
../../third_party/breakpad/breakpad/src/client/linux/handler/exception_handler_unittest.cc:267:43: error: unknown type name 'pthread_barrier_t'; did you mean 'pthread_attr_t'?
  pthread_barrier_t* b = reinterpret_cast<pthread_barrier_t*>(b_ptr);
                                          ^~~~~~~~~~~~~~~~~
                                          pthread_attr_t
../../third_party/android_ndk/sysroot/usr/include/bits/pthread_types.h:45:3: note: 'pthread_attr_t' declared here
} pthread_attr_t;
  ^
../../third_party/breakpad/breakpad/src/client/linux/handler/exception_handler_unittest.cc:268:3: error: use of undeclared identifier 'pthread_barrier_wait'
  pthread_barrier_wait(b);
  ^
3 errors generated.

Patch-set: 3