linux/handler: fix ambiguous max argument error
Starting with glibc 2.34 SIGSTKSZ is not constant anymore
so builds will fail because the compiler can't infer the
type of the max() arguments, so we have to specify them.

Example failure:
.../src/client/linux/handler/exception_handler.cc:141:41:
error: no matching function for call to 'max'
static const unsigned kSigStackSize = std::max(16384, SIGSTKSZ);

BUG=b:235960683
TEST=Local build with glibc >= 2.34.

Change-Id: I298735e9a935f81ad7777ca09e400fd92b88dfd8